#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`

OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

#OLDGOROOT="$GOROOT"
#export GOROOT="$CURDIR"

gofmt -tabs=false -tabwidth=4 -w src
go install pp_server pp_client

export GOPATH="$OLDGOPATH"
#export GOROOT="$OLDGOROOT"

echo 'finished'
